"use client";

import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "@mantine/core/styles.css";
import "./globals.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { ApolloProvider } from "@apollo/client";
import { client } from "../apollo-client";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className={`${fontSans.variable}`}>
      <ApolloProvider client={client}>
        <head>
          <link rel="icon" href="/favicon.ico" sizes="any" />
          <link
            rel="apple-touch-icon"
            href="/apple-touch-icon.png"
            type="image/png"
            sizes="180x180"
          />
          <ColorSchemeScript />
        </head>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          <MantineProvider
            theme={{
              fontFamily: "var(--font-sans)",
            }}
          >
            <div className="flex min-h-[calc(100vh_-_64px)]">{children}</div>
          </MantineProvider>
        </body>
      </ApolloProvider>
    </html>
  );
}
