'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@mantine/core/styles.css";
import "./globals.css";
import { MantineProvider } from "@mantine/core";
import { ApolloProvider } from "@apollo/client";
import { client } from "../apollo-client";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ApolloProvider client={client}>
        <body className={inter.className}>
          <MantineProvider>{children}</MantineProvider>
        </body>
      </ApolloProvider>
    </html>
  );
}
